import { AvenirNextFont } from '../utils/fonts';
import { AppProvider } from './providers';

export const metadata = {
  title: 'Resona',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={AvenirNextFont.className}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
