import { AppThemeProvider } from '@resona/theme';

import { AvenirNextFont } from '../utils/fonts';

export const metadata = {
  title: 'Resona',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={AvenirNextFont.className}>
        <AppThemeProvider>{children}</AppThemeProvider>
      </body>
    </html>
  );
}
